import { defineObject, FieldType } from 'twenty-sdk/define';

import {
  QUOTE_OBJECT_UNIVERSAL_IDENTIFIER,
  QUOTE_DOCUMENT_NUMBER_FIELD_UNIVERSAL_IDENTIFIER,
  QUOTE_REVISION_FIELD_UNIVERSAL_IDENTIFIER,
  QUOTE_STATUS_FIELD_UNIVERSAL_IDENTIFIER,
  QUOTE_ISSUED_AT_FIELD_UNIVERSAL_IDENTIFIER,
  QUOTE_VALID_UNTIL_FIELD_UNIVERSAL_IDENTIFIER,
  QUOTE_ACCEPTED_AT_FIELD_UNIVERSAL_IDENTIFIER,
  QUOTE_ACCEPTED_BY_NAME_FIELD_UNIVERSAL_IDENTIFIER,
  QUOTE_ACCEPTED_VIA_FIELD_UNIVERSAL_IDENTIFIER,
  QUOTE_SHARE_TOKEN_FIELD_UNIVERSAL_IDENTIFIER,
  QUOTE_SUBTOTAL_FIELD_UNIVERSAL_IDENTIFIER,
  QUOTE_DISCOUNT_TYPE_FIELD_UNIVERSAL_IDENTIFIER,
  QUOTE_DISCOUNT_VALUE_FIELD_UNIVERSAL_IDENTIFIER,
  QUOTE_TAX_LABEL_FIELD_UNIVERSAL_IDENTIFIER,
  QUOTE_TAX_RATE_FIELD_UNIVERSAL_IDENTIFIER,
  QUOTE_IS_TAX_REGISTERED_FIELD_UNIVERSAL_IDENTIFIER,
  QUOTE_TOTAL_FIELD_UNIVERSAL_IDENTIFIER,
  QUOTE_TERMS_FIELD_UNIVERSAL_IDENTIFIER,
  QUOTE_ISSUER_SNAPSHOT_FIELD_UNIVERSAL_IDENTIFIER,
  QUOTE_BILL_TO_SNAPSHOT_FIELD_UNIVERSAL_IDENTIFIER,
} from 'src/constants/quote-identifiers';

/**
 * A quotation sent to a client.
 *
 * Lifecycle, ported from Gotka: a quote is editable only while DRAFT. Issuing it
 * assigns the continuous document number, freezes the issuer and bill-to details
 * onto the record, and mints the share token the client opens. After that the
 * quote is immutable - a change means a new revision that supersedes it.
 */
export default defineObject({
  universalIdentifier: QUOTE_OBJECT_UNIVERSAL_IDENTIFIER,
  nameSingular: 'quote',
  namePlural: 'quotes',
  labelSingular: 'Quote',
  labelPlural: 'Quotes',
  description: 'A quotation issued to a client',
  icon: 'IconFileDollar',
  fields: [
    {
      universalIdentifier: QUOTE_DOCUMENT_NUMBER_FIELD_UNIVERSAL_IDENTIFIER,
      name: 'documentNumber',
      type: FieldType.TEXT,
      label: 'Number',
      description: 'Continuous number assigned at issue, e.g. Q-0001. Empty while draft.',
      icon: 'IconHash',
    },
    {
      universalIdentifier: QUOTE_REVISION_FIELD_UNIVERSAL_IDENTIFIER,
      name: 'revision',
      type: FieldType.NUMBER,
      label: 'Revision',
      description: 'Revision number. A revised quote keeps its number and increments this.',
      icon: 'IconVersions',
      defaultValue: 1,
    },
    {
      universalIdentifier: QUOTE_STATUS_FIELD_UNIVERSAL_IDENTIFIER,
      name: 'status',
      type: FieldType.SELECT,
      label: 'Status',
      description: 'Where the quote is in its lifecycle',
      icon: 'IconProgressCheck',
      defaultValue: "'DRAFT'",
      options: [
        { value: 'DRAFT', label: 'Draft', position: 0, color: 'gray' },
        { value: 'ISSUED', label: 'Issued', position: 1, color: 'blue' },
        { value: 'ACCEPTED', label: 'Accepted', position: 2, color: 'green' },
        { value: 'DECLINED', label: 'Declined', position: 3, color: 'red' },
        { value: 'EXPIRED', label: 'Expired', position: 4, color: 'orange' },
        { value: 'WITHDRAWN', label: 'Withdrawn', position: 5, color: 'gray' },
        { value: 'SUPERSEDED', label: 'Superseded', position: 6, color: 'purple' },
      ],
    },
    {
      universalIdentifier: QUOTE_ISSUED_AT_FIELD_UNIVERSAL_IDENTIFIER,
      name: 'issuedAt',
      type: FieldType.DATE_TIME,
      label: 'Issued at',
      description: 'When the quote was issued. Set once, never changed.',
      icon: 'IconSend',
    },
    {
      universalIdentifier: QUOTE_VALID_UNTIL_FIELD_UNIVERSAL_IDENTIFIER,
      name: 'validUntil',
      type: FieldType.DATE,
      label: 'Valid until',
      description: 'Expiry date. Can be extended while the quote is still open.',
      icon: 'IconCalendarX',
    },
    {
      universalIdentifier: QUOTE_ACCEPTED_AT_FIELD_UNIVERSAL_IDENTIFIER,
      name: 'acceptedAt',
      type: FieldType.DATE_TIME,
      label: 'Accepted at',
      icon: 'IconCheck',
    },
    {
      universalIdentifier: QUOTE_ACCEPTED_BY_NAME_FIELD_UNIVERSAL_IDENTIFIER,
      name: 'acceptedByName',
      type: FieldType.TEXT,
      label: 'Accepted by',
      description: 'Name the client typed when accepting',
      icon: 'IconSignature',
    },
    {
      universalIdentifier: QUOTE_ACCEPTED_VIA_FIELD_UNIVERSAL_IDENTIFIER,
      name: 'acceptedVia',
      type: FieldType.SELECT,
      label: 'Accepted via',
      description: 'How the acceptance arrived. Not every client uses the link.',
      icon: 'IconRoute',
      options: [
        { value: 'LINK', label: 'Share link', position: 0, color: 'green' },
        { value: 'WHATSAPP', label: 'WhatsApp', position: 1, color: 'turquoise' },
        { value: 'EMAIL', label: 'Email', position: 2, color: 'blue' },
        { value: 'PURCHASE_ORDER', label: 'Purchase order', position: 3, color: 'purple' },
      ],
    },
    {
      universalIdentifier: QUOTE_SHARE_TOKEN_FIELD_UNIVERSAL_IDENTIFIER,
      name: 'shareToken',
      type: FieldType.TEXT,
      label: 'Share token',
      description: 'Secret path segment for the public quote page',
      icon: 'IconLink',
      defaultValue: 'uuid',
    },
    {
      universalIdentifier: QUOTE_SUBTOTAL_FIELD_UNIVERSAL_IDENTIFIER,
      name: 'subtotal',
      type: FieldType.CURRENCY,
      label: 'Subtotal',
      description: 'Sum of line amounts before discount and tax',
      icon: 'IconSum',
    },
    {
      universalIdentifier: QUOTE_DISCOUNT_TYPE_FIELD_UNIVERSAL_IDENTIFIER,
      name: 'discountType',
      type: FieldType.SELECT,
      label: 'Discount type',
      icon: 'IconDiscount',
      defaultValue: "'NONE'",
      options: [
        { value: 'NONE', label: 'None', position: 0, color: 'gray' },
        { value: 'PERCENT', label: 'Percent', position: 1, color: 'blue' },
        { value: 'AMOUNT', label: 'Amount', position: 2, color: 'purple' },
      ],
    },
    {
      universalIdentifier: QUOTE_DISCOUNT_VALUE_FIELD_UNIVERSAL_IDENTIFIER,
      name: 'discountValue',
      type: FieldType.NUMBER,
      label: 'Discount value',
      description: 'Percent when discount type is PERCENT, otherwise a flat amount',
      icon: 'IconPercentage',
      defaultValue: 0,
    },
    {
      universalIdentifier: QUOTE_TAX_LABEL_FIELD_UNIVERSAL_IDENTIFIER,
      name: 'taxLabel',
      type: FieldType.TEXT,
      label: 'Tax label',
      description: 'What the tax is called on the document, e.g. SST',
      icon: 'IconReceiptTax',
      defaultValue: "'SST'",
    },
    {
      universalIdentifier: QUOTE_TAX_RATE_FIELD_UNIVERSAL_IDENTIFIER,
      name: 'taxRate',
      type: FieldType.NUMBER,
      label: 'Tax rate',
      description: 'Percent. Only applied when the business is tax registered.',
      icon: 'IconPercentage',
      defaultValue: 0,
    },
    {
      universalIdentifier: QUOTE_IS_TAX_REGISTERED_FIELD_UNIVERSAL_IDENTIFIER,
      name: 'isTaxRegistered',
      type: FieldType.BOOLEAN,
      label: 'Tax registered',
      description: 'Tax is built in but stays off until the business registers',
      icon: 'IconCertificate',
      defaultValue: false,
    },
    {
      universalIdentifier: QUOTE_TOTAL_FIELD_UNIVERSAL_IDENTIFIER,
      name: 'total',
      type: FieldType.CURRENCY,
      label: 'Total',
      description: 'Final amount. An accepted quote can push this onto the opportunity.',
      icon: 'IconCurrencyDollar',
    },
    {
      universalIdentifier: QUOTE_TERMS_FIELD_UNIVERSAL_IDENTIFIER,
      name: 'terms',
      type: FieldType.TEXT,
      label: 'Terms',
      description: 'Payment terms printed on the document',
      icon: 'IconFileText',
    },
    {
      universalIdentifier: QUOTE_ISSUER_SNAPSHOT_FIELD_UNIVERSAL_IDENTIFIER,
      name: 'issuerSnapshot',
      type: FieldType.RAW_JSON,
      label: 'Issuer snapshot',
      description:
        'Business name, registration number and address frozen at issue, so a later settings change never rewrites an issued document.',
      icon: 'IconBuildingStore',
    },
    {
      universalIdentifier: QUOTE_BILL_TO_SNAPSHOT_FIELD_UNIVERSAL_IDENTIFIER,
      name: 'billToSnapshot',
      type: FieldType.RAW_JSON,
      label: 'Bill to snapshot',
      description: 'Client company and contact details frozen at issue',
      icon: 'IconAddressBook',
    },
  ],
});
